.\" Man page for client program
.TH MYCAT 3 "22 Sep 2025" "v0.4.1-final" "Client Program Manual"
.SH NAME
mycat \- sample client program demonstrating static/dynamic linking
.SH SYNOPSIS
.B client
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B client
is a sample program that demonstrates the use of static and dynamic libraries.
It prints messages, counts lines in files, and showcases utility functions.
.SH AUTHOR
Muhammad Shahid <shahidmolecules@gmail.com>
